spring:
  cloud:
    stream:
      bindings:
        myMessage:
         group: order
         content-type: application/json
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
  sleuth:
    sampler:
      #抽样数据
      probability: 1


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#feign中的hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  context-path: /
logging:
  level:
    org.springframework.cloud.openfeign: debug   